<p style="font-size: 20px; color:#00ff00; text-align: center">
    Importando Numpy

In [1]:
import numpy as np

<p style="font-size: 20px; color:#00ff00; text-align: center">
    Criando arrays de 1, 2 e 3 dimensoes

In [ ]:
arr1 = np.array([1,3,5,7,9])
arr2 = np.array([2,4,6,8,10])
arr3 = np.array([[1,2,3] , [2,4,3]])
arr3

array([[1, 2, 3],
       [2, 4, 3]])

<p style="font-size: 20px; color:#00ff00; text-align: center">
    Atributos de um array

In [ ]:
# arr3.shape
# arr3.ndim
# arr3.dtype
# arr3.size

6

<p style="font-size: 20px; color:#00ff00; text-align: center">
    Slice (Fatiamento)

In [12]:
arr3[1, 2]

3

<p style="font-size: 20px; color:#00ff00; text-align: center">
    Operações aritméticas

In [16]:
arr4 = np.array([2,2,2])
arr5 = np.array([4,4,4])

arr4 + arr5

array([6, 6, 6])

<p style="font-size: 20px; color:#00ff00; text-align: center">
    Multiplicando valores sem uso de loops

In [17]:
arr5 * 10

array([40, 40, 40])

<p style="font-size: 20px; color:#00ff00; text-align: center">
    Calculando raiz quadrada de cada elemento

In [19]:
a = np.sqrt(np.array([1,9,4,16]))
a

array([1., 3., 2., 4.])

<p style="font-size: 20px; color:#00ff00; text-align: center">
Criando arrays apartir de funções

In [ ]:
# np.zeros((3,3))
# np.ones((5,5))
# dados = np.arange(0, 100, 5)
# np.linspace(0 , 1, 5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])